### ISSUE TITLE
Use respec by default when running rake in Rails apps?

### ISSUE THREAD

**Issue by jmuheim** [oggy/respec#10]
I know that I can create a task like this:

```ruby
task(:default).clear
task default: :'spec:respec'

namespace :spec do
  desc 'Run all specs in spec directory (with Fuubar formatter)'
  task :respec do
    `respec`
  end
end
```

But this won't run the stuff in the same process (I guess). Is there another way?

**Comment by oggy** [comment]
Updating your rake tasks feels outside the scope of respec right now. At the moment, it's not even expected that you put respec in a project's Gemfile.

I suggest you propose to the RSpec team a way of updating the spec executable path more easily. This is the only thing I could come up with without monkeypatching:

    ObjectSpace.each_object(RSpec::Core::RakeTask).each { |t| t.rspec_path = 'respec' }
